Zap 27 UI client core
UwUClub/Zappy pull request #17
Opened 2023-05-25 13:10 UTC by Valegox

## Describe your changes

Add API class that connects to the server and handles read / write buffers.

## Issue ticket number and link

https://uwuclub.atlassian.net/browse/ZAP-27?atlOrigin=eyJpIjoiN2ZkZTNmMjI4MTQ3NGNiNDg5MmU0ODYyNjc2M2ZmMzIiLCJwIjoiaiJ9

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have documented my code
- [ ] Do we need to implement unit tests?

2023-05-25 15:07 UTC, Beafowl-Pull approved these changes

2023-05-26 08:17 UTC, GlassAlo requested changes

2023-05-26 08:17 UTC, GlassAlo commented on src/gui/cli/ParserData.cpp
> +        return _machineName;
const ref

2023-05-26 08:17 UTC, GlassAlo commented on src/gui/cli/ParserData.cpp
> +    std::string ParserData::getAddress() const
const ref

2023-05-26 08:17 UTC, GlassAlo commented on src/gui/cli/ParserData.cpp
> +    ParserData::ParserData(std::string aAddress, unsigned int aPort, std::string aMachineName)
soit const ref pour les str

soit std::move
ParserData::ParserData(std::string aAddress, unsigned int aPort, std::string aMachineName) : 
     _address(std::move(aAddress))

2023-05-26 08:17 UTC, GlassAlo commented on src/gui/cli/ServerData.hpp
> +        std::pair<unsigned int, unsigned int> _playerPosition;
une class player
remplacer par vector de cette class

2023-05-26 08:17 UTC, GlassAlo commented on src/gui/main.cpp
>  int main(__attribute__((unused)) int argc, __attribute__((unused)) char **argv)
[[maybe_unused]]

2023-05-26 16:16 UTC, GlassAlo requested changes

2023-05-26 16:16 UTC, GlassAlo commented on src/gui/cli/ParserData.cpp
> +        int opt = 0;
var nommage convention

2023-05-26 16:16 UTC, GlassAlo commented on src/gui/cli/ParserData.hpp
> +            void parseData(int argc, char **argv);
var nommage convention

2023-05-26 16:16 UTC, GlassAlo commented on src/gui/cli/Player.hpp
> +#define INVENTORY_SIZE 7
replace with
const constexpr int INVENTORY_SIZE = 7
or
const constexpr uin8_t INVENTORY_SIZE = 7
(not sure about the uint8_t, find the good one)

2023-05-26 17:25 UTC, GlassAlo requested changes
Gimme the zappy_ai back

2023-05-26 17:31 UTC, GlassAlo approved these changes

2023-05-26 17:32 UTC, merged