ZAP 99 Connect_nbr
UwUClub/Zappy pull request #54
Opened 2023-06-02 10:05 UTC by BaptisteLaran

## Describe your changes

Add Connect_nbr command

## Issue ticket number and link

https://uwuclub.atlassian.net/browse/ZAP-99?atlOrigin=eyJpIjoiNGVkZmExNDJhMjcyNGFmMDkyODFkODdhZjM1ZDYwMjciLCJwIjoiaiJ9

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have documented my code
- [ ] Do we need to implement unit tests?

2023-06-02 11:33 UTC, christophechr approved these changes

2023-06-02 14:55 UTC, Valegox requested changes

2023-06-02 14:55 UTC, Valegox commented on src/server/implementation/cmd_parser.c
> +    {"Connect_nbr", &connect_nbr},
This file is outdated, please delete it. Add `connect_nbr` to `player_cmd_scheduler.c`.

2023-06-02 14:55 UTC, Valegox commented on src/server/implementation/ia/connect_nbr.c
> +}
Please add a scheduler function for connect_nbr (its delay will be 0)

2023-06-02 14:55 UTC, Valegox commented on src/server/implementation/ia/connect_nbr.c
> +    if (args != NULL) {
The arg check should be done in the scheduler

2023-06-02 16:16 UTC, christophechr approved these changes

2023-06-03 08:15 UTC, Valegox approved these changes

2023-06-04 22:20 UTC, merged