Zap 22 fork
UwUClub/Zappy pull request #89
Opened 2023-06-07 18:08 UTC by Valegox

## Describe your changes

On server side

- Add eggs (enw, food consumption, hatch, death)
- pfk / enw / ebo / edi
- Refactor player connection
- Add `id` attribute to players
- Add `Fork` command that creates a new egg

## Issue ticket number and link

https://uwuclub.atlassian.net/browse/ZAP-22?atlOrigin=eyJpIjoiNDgxOTQwYWFmZGRiNDU2OThhMjY5Y2Y3NGM1YmQ2OTIiLCJwIjoiaiJ9

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have documented my code
- [ ] Do we need to implement unit tests?

2023-06-07 18:38 UTC, GlassAlo requested changes
1 commentary to be addressed

2023-06-07 18:38 UTC, GlassAlo commented on src/server/core/server_data/init_map.c
> +
Space

2023-06-07 18:43 UTC, christophechr approved these changes

2023-06-08 07:52 UTC, GlassAlo approved these changes

2023-06-08 07:52 UTC, merged